=begin
#API

#REST API to manage Reepay resources

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Reepay::AdditionalCostApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AdditionalCostApi' do
  before do
    # run before each test
    @instance = Reepay::AdditionalCostApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdditionalCostApi' do
    it 'should create an instance of AdditionalCostApi' do
      expect(@instance).to be_instance_of(Reepay::AdditionalCostApi)
    end
  end

  # unit tests for cancel_additional_cost
  # Cancel pending additional cost
  # 
  # @param handle Additonal cost handle
  # @param [Hash] opts the optional parameters
  # @return [AdditionalCost]
  describe 'cancel_additional_cost test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_additional_cost_json
  # Create additional cost
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateAdditionalCost] :body 
  # @return [AdditionalCost]
  describe 'create_additional_cost_json test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_additional_cost
  # Get additional cost
  # 
  # @param handle Additonal cost handle
  # @param [Hash] opts the optional parameters
  # @return [AdditionalCost]
  describe 'get_additional_cost test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_additional_costs
  # Get additional costs for subscription
  # 
  # @param handle Subscription handle
  # @param [Hash] opts the optional parameters
  # @return [Array<AdditionalCost>]
  describe 'get_additional_costs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
