=begin
#API

#REST API to manage Reepay resources

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Reepay::AuthenticateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthenticateApi' do
  before do
    # run before each test
    @instance = Reepay::AuthenticateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticateApi' do
    it 'should create an instance of AuthenticateApi' do
      expect(@instance).to be_instance_of(Reepay::AuthenticateApi)
    end
  end

  # unit tests for login
  # User login
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :email User email
  # @option opts [String] :password User password
  # @option opts [String] :organisation Organisation subdomain to login to
  # @option opts [String] :account Account handle or id to login to
  # @return [UserLogin]
  describe 'login test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for renew
  # Renew user login
  # 
  # @param [Hash] opts the optional parameters
  # @return [UserRenew]
  describe 'renew test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for verify_authentication
  # Verify authentication
  # 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'verify_authentication test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
