=begin
#API

#REST API to manage Reepay resources

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Reepay::DiscountApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DiscountApi' do
  before do
    # run before each test
    @instance = Reepay::DiscountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DiscountApi' do
    it 'should create an instance of DiscountApi' do
      expect(@instance).to be_instance_of(Reepay::DiscountApi)
    end
  end

  # unit tests for create_discount
  # Create discount
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateDiscount] :body 
  # @return [Discount]
  describe 'create_discount test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_discount
  # Delete discount
  # 
  # @param handle Discount handle
  # @param [Hash] opts the optional parameters
  # @return [Discount]
  describe 'delete_discount test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_discount
  # Get discount
  # 
  # @param handle Discount handle
  # @param [Hash] opts the optional parameters
  # @return [Discount]
  describe 'get_discount test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_discounts
  # Get list of discounts
  # 
  # @param page Page number to get
  # @param size Page size to use
  # @param search Optional search expression
  # @param sort Optional sorting expression
  # @param [Hash] opts the optional parameters
  # @return [DiscountSearch]
  describe 'get_discounts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for undelete_discount
  # Undelete discount
  # 
  # @param handle Discount handle
  # @param [Hash] opts the optional parameters
  # @return [Discount]
  describe 'undelete_discount test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
