=begin
#API

#REST API to manage Reepay resources

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Reepay::MailTemplateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MailTemplateApi' do
  before do
    # run before each test
    @instance = Reepay::MailTemplateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MailTemplateApi' do
    it 'should create an instance of MailTemplateApi' do
      expect(@instance).to be_instance_of(Reepay::MailTemplateApi)
    end
  end

  # unit tests for get_sample
  # Get sample data
  # 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_sample test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
