=begin
#API

#REST API to manage Reepay resources

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Reepay::OrganisationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OrganisationApi' do
  before do
    # run before each test
    @instance = Reepay::OrganisationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrganisationApi' do
    it 'should create an instance of OrganisationApi' do
      expect(@instance).to be_instance_of(Reepay::OrganisationApi)
    end
  end

  # unit tests for get_organisation
  # Get organisation
  # 
  # @param [Hash] opts the optional parameters
  # @return [Organisation]
  describe 'get_organisation test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Update organisation
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateOrganisation] :body 
  # @return [Organisation]
  describe 'update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
