=begin
#API

#REST API to manage Reepay resources

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Reepay::ExpireSubscription
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExpireSubscription' do
  before do
    # run before each test
    @instance = Reepay::ExpireSubscription.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExpireSubscription' do
    it 'should create an instance of ExpireSubscription' do
      expect(@instance).to be_instance_of(Reepay::ExpireSubscription)
    end
  end
  describe 'test attribute "compensation_method"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["full_refund", "prorated_refund", "none"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.compensation_method = value }.not_to raise_error
       #end
    end
  end

end

