=begin
#API

#REST API to manage Reepay resources

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Reepay::RedeemCouponCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RedeemCouponCode' do
  before do
    # run before each test
    @instance = Reepay::RedeemCouponCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RedeemCouponCode' do
    it 'should create an instance of RedeemCouponCode' do
      expect(@instance).to be_instance_of(Reepay::RedeemCouponCode)
    end
  end
  describe 'test attribute "code"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

